site_name: My Docs
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started:
    - Math: start/math.md
    - Securities: start/securities.md
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js